# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

add_diag_double <- function(x, epsilon) {
    invisible(.Call('dmisc_add_diag_double', PACKAGE = 'dmisc', x, epsilon))
}

add_diag_double_vec <- function(x, epsilon) {
    invisible(.Call('dmisc_add_diag_double_vec', PACKAGE = 'dmisc', x, epsilon))
}

add_diag_int <- function(x, epsilon) {
    invisible(.Call('dmisc_add_diag_int', PACKAGE = 'dmisc', x, epsilon))
}

add_diag_int_vec <- function(x, epsilon) {
    invisible(.Call('dmisc_add_diag_int_vec', PACKAGE = 'dmisc', x, epsilon))
}

col_scale_inplace <- function(x, center, scale) {
    invisible(.Call('dmisc_col_scale_inplace', PACKAGE = 'dmisc', x, center, scale))
}

col_scale_copy <- function(x, center, scale) {
    .Call('dmisc_col_scale_copy', PACKAGE = 'dmisc', x, center, scale)
}

#' @export
prob_recomb <- function(x) {
    .Call('dmisc_prob_recomb', PACKAGE = 'dmisc', x)
}

#' @export
segr_var <- function(pat, mat, pos, p, alpha) {
    .Call('dmisc_segr_var', PACKAGE = 'dmisc', pat, mat, pos, p, alpha)
}

match_dbl_cpp <- function(x, table, nomatch, tolerance) {
    .Call('dmisc_match_dbl_cpp', PACKAGE = 'dmisc', x, table, nomatch, tolerance)
}

nth_partial_sort <- function(x, nth, increasing = TRUE) {
    .Call('dmisc_nth_partial_sort', PACKAGE = 'dmisc', x, nth, increasing)
}

stl_partial_sort <- function(x, n, increasing = TRUE) {
    .Call('dmisc_stl_partial_sort', PACKAGE = 'dmisc', x, n, increasing)
}

#' @export
routine <- function(vec) {
    .Call('dmisc_routine', PACKAGE = 'dmisc', vec)
}

#' @export
string_collapse <- function(data) {
    .Call('dmisc_string_collapse', PACKAGE = 'dmisc', data)
}

topN_rcpp <- function(x, nth) {
    .Call('dmisc_topN_rcpp', PACKAGE = 'dmisc', x, nth)
}

